/**
 * Is this release one the installed app can actually update from?
 *
 * ---------------------------------------------------------------------------
 * WHY THIS EXISTS.
 *
 * From the boot log of the RedBot installed on Clark's machine, 2026-08-12, four times in
 * thirty-five seconds:
 *
 *   ERROR updater  Cannot find latest.yml in the latest release artifacts
 *                  (.../releases/download/v2.0.2/latest.yml): HttpError: 404
 *
 * The app said the right thing. Nobody was listening, because the app is the last place this can
 * be discovered: by then the release is published, the installer is downloaded, and every machine
 * on that version has quietly stopped updating. Two weeks later that install is still on 2.0.2 and
 * the only way to move it is to hand somebody a file.
 *
 * electron-builder.yml already carries three traps in its comments, each written after it cost
 * something:
 *   - the installer on disk is `redbot Setup 3.5.1.exe` and latest.yml names
 *     `redbot-Setup-3.5.1.exe`; upload the disk name and the updater 404s forever;
 *   - the nsis-web STUB is written under the same artifactName as the full installer — 726,824
 *     bytes where 103 MB is expected — so publishing it makes every update install a downloader;
 *   - a DRAFT release is invisible to the updater while looking published.
 *
 * A comment cannot fail a build. This can. It reads the release the way the updater reads it, and
 * reports what the updater would find.
 *
 *   node tools/release/verify-release.mjs             # the newest release
 *   node tools/release/verify-release.mjs v3.5.1      # a specific tag
 *
 * Exit 0 when an installed app could update from it, 1 when it could not, 2 when the release
 * could not be read at all (which is not the same as a bad release, and does not pretend to be).
 * ---------------------------------------------------------------------------
 */

import { pathToFileURL } from 'node:url';

/** The repository electron-builder publishes to, and src/update.ts reads. One source, not two. */
export const REPO = 'jerome653/redbot';

/**
 * The few fields of latest.yml that decide whether an update can happen.
 *
 * A hand-written reader rather than a YAML dependency: this file is generated by
 * electron-builder to a fixed shape, the whole product has two runtime dependencies, and adding a
 * parser to a build script that reads six lines is the wrong trade. Anything it cannot find comes
 * back null, and null is reported as a missing field rather than guessed at.
 */
export function readLatestYml(text) {
  const one = (re) => { const m = re.exec(text ?? ''); return m ? m[1].trim().replace(/^['"]|['"]$/g, '') : null; };
  const files = [];
  const block = /^\s*-\s+url:\s*(.+)$/gm;
  let m;
  while ((m = block.exec(text ?? '')) !== null) {
    const after = text.slice(m.index);
    const size = /\n\s+size:\s*(\d+)/.exec(after);
    files.push({ url: m[1].trim().replace(/^['"]|['"]$/g, ''), size: size ? Number(size[1]) : null });
  }
  return {
    version: one(/^version:\s*(.+)$/m),
    path: one(/^path:\s*(.+)$/m),
    sha512: one(/^sha512:\s*(.+)$/m),
    files
  };
}

/**
 * Everything that has to be true for an installed app to update from this release.
 *
 * Pure, so every trap below is a test rather than a release. `assets` is the release's asset list
 * as GitHub reports it: `{ name, size }`.
 */
export function verifyRelease({ tag, draft = false, prerelease = false, assets = [], latestYml = null }) {
  const problems = [];
  const names = new Map(assets.map((a) => [a.name, a]));

  /* A draft appears in neither the releases feed nor /releases/latest: the updater reports "no
     published versions" while the release sits there looking published. */
  if (draft) problems.push('the release is a DRAFT — the updater cannot see it at all');

  if (!names.has('latest.yml')) {
    problems.push('latest.yml is not attached — this is the 404 every install hits, forever');
    return { ok: false, problems, installer: null };
  }
  if (latestYml === null) {
    problems.push('latest.yml is attached but could not be read');
    return { ok: false, problems, installer: null };
  }

  const y = readLatestYml(latestYml);
  for (const [field, value] of [['version', y.version], ['path', y.path], ['sha512', y.sha512]]) {
    if (!value) problems.push(`latest.yml has no ${field}:`);
  }

  /* The tag and the version inside the manifest must agree, or the updater compares against a
     number this release does not contain. */
  const tagVersion = String(tag ?? '').replace(/^v/, '');
  if (y.version && tagVersion && y.version !== tagVersion) {
    problems.push(`latest.yml says version ${y.version} but the tag is ${tag}`);
  }

  /* THE FILENAME TRAP. latest.yml names the file the updater will fetch; if the asset was uploaded
     under its on-disk name (spaces, not hyphens) the fetch 404s and the release looks complete. */
  const installer = y.path ? names.get(y.path) ?? null : null;
  if (y.path && !installer) {
    const near = assets.map((a) => a.name).filter((n) => n.toLowerCase().endsWith('.exe'));
    problems.push(
      `latest.yml points at "${y.path}" and no asset has that name` +
      (near.length ? ` — the release has ${near.map((n) => `"${n}"`).join(', ')}` : '')
    );
  }

  /* THE STUB TRAP. The nsis-web downloader is ~700 KB where the installer is ~100 MB. Sizes come
     from the manifest itself, so this compares the release against its own claim. */
  for (const f of y.files) {
    const asset = names.get(f.url);
    if (!asset) { problems.push(`latest.yml lists "${f.url}" and no asset has that name`); continue; }
    if (f.size !== null && asset.size !== null && f.size !== asset.size) {
      problems.push(
        `"${f.url}" is ${asset.size} bytes on the release and ${f.size} in latest.yml` +
        (asset.size < f.size / 10 ? ' — that size difference is the web stub uploaded as the installer' : '')
      );
    }
  }

  /* The blockmap is what makes a differential download possible. Its absence does not break
     updating — electron-updater falls back to the full download — so it is a problem worth
     naming and not a refusal on its own. */
  const blockmapMissing = y.path && !names.has(`${y.path}.blockmap`);

  return {
    ok: problems.length === 0,
    problems,
    warnings: blockmapMissing
      ? [`${y.path}.blockmap is not attached — updates will fall back to a full download`]
      : [],
    prerelease,
    installer
  };
}

/* ------------------------------------------------------------------ *
 * Running it against the real repository
 * ------------------------------------------------------------------ */

async function api(path) {
  const headers = { accept: 'application/vnd.github+json', 'user-agent': 'redbot-verify-release' };
  /* Anonymous works on a public repo; a token, if the shell has one, only buys a higher rate. */
  if (process.env.GITHUB_TOKEN) headers.authorization = `Bearer ${process.env.GITHUB_TOKEN}`;
  const res = await fetch(`https://api.github.com${path}`, { headers });
  if (!res.ok) throw new Error(`GitHub answered ${res.status} for ${path}`);
  return res.json();
}

async function main() {
  const tag = process.argv[2];
  let release;
  try {
    release = tag
      ? await api(`/repos/${REPO}/releases/tags/${tag}`)
      : (await api(`/repos/${REPO}/releases?per_page=1`))[0];
  } catch (e) {
    console.error(`  X   could not read the release: ${e instanceof Error ? e.message : String(e)}`);
    return 2;
  }
  if (!release) { console.error('  X   this repository has no releases'); return 2; }

  const assets = (release.assets ?? []).map((a) => ({ name: a.name, size: a.size }));
  let latestYml = null;
  const manifest = (release.assets ?? []).find((a) => a.name === 'latest.yml');
  if (manifest) {
    try {
      const res = await fetch(manifest.browser_download_url, { headers: { 'user-agent': 'redbot-verify-release' } });
      if (res.ok) latestYml = await res.text();
    } catch { /* reported as unreadable below */ }
  }

  const v = verifyRelease({ tag: release.tag_name, draft: release.draft, prerelease: release.prerelease, assets, latestYml });

  console.log(`\nrelease ${release.tag_name} · ${assets.length} asset(s)\n${'-'.repeat(40)}`);
  for (const p of v.problems) console.log(`  X   ${p}`);
  for (const w of v.warnings ?? []) console.log(`  !   ${w}`);
  if (v.ok) {
    console.log('  OK  an installed app can update from this release.');
    if (v.installer) console.log(`      ${v.installer.name} · ${v.installer.size} bytes`);
  }
  console.log();
  return v.ok ? 0 : 1;
}

/* Run only when invoked as the program: importing this from the test must not start a fetch.
   `file://${argv[1]}` is not the same string as import.meta.url on Windows (drive letters and
   backslashes), so the comparison goes through pathToFileURL rather than string-building. */
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  main().then((code) => process.exit(code));
}
