/**
 * PHASE 4 — anti-leakage fuzz.
 *
 * A corpus of leakage the model has produced, plus adversarial variants it has not yet
 * produced but plausibly could. Every MUST_BLOCK entry that passes the linter is a release
 * blocker. Every MUST_PASS entry that the linter rejects is a false positive that would
 * make the tool unusable.
 *
 * Costs no LLM calls — pure linter validation.
 *
 * Run: node qa/phase4-fuzz.mjs
 */
import { lintDraft } from '../dist/disclosure.js';
import { writeFileSync, appendFileSync, mkdirSync } from 'node:fs';
import { dirname } from 'node:path';

const OUT = 'qa/evidence/phase4-fuzz.log';
/* qa/evidence/ has no tracked files, so it does not exist on a fresh clone and every
   gate here used to crash with ENOENT before running a single check (B2). */
mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, `PHASE 4 — anti-leakage fuzz\n${new Date().toISOString()}\n\n`);
const log = (s) => { console.log(s); appendFileSync(OUT, s + '\n'); };

const REAL = `Check whether object caching is actually connected before blaming the theme.
Run wp cache flush and watch whether the query count in Query Monitor drops. If it does not,
the drop-in is not wired up and everything downstream is guesswork.`;

/** Every one of these MUST be blocked. */
const MUST_BLOCK = [
  // --- observed in the wild (round 1 + 2) ---
  ['observed: plan file note', 'Plan file done. ExitPlanMode tool unavailable here — delivering direct.\n\n' + REAL],
  ['observed: saved plan path', REAL + '\n\nFull plan+rule-check saved: C:\\Users\\JerOme\\.claude\\plans\\x.md'],
  ['observed: cwd + memory flag', REAL + '\n\nFlag: cwd (Projects/redbot) matches the astroturf-risk pattern noted in memory.'],
  ['observed: draft preamble', 'Draft below, WP Super Cache diagnosis angle, ready to edit/post.\n\n' + REAL],
  ['observed: plan written', 'Plan written with the drafted reply. Ready for you to review or request edits.'],

  // --- adversarial variants ---
  ['adv: posix home path', REAL + '\n\nSee /home/jerome/projects/redbot/src/config.ts for the setting.'],
  ['adv: mac home path', REAL + '\n\nCheck /Users/jerome/redbot/data/threads.json'],
  ['adv: repo name', REAL + '\n\n(generated by redbot from the SGEN repo)'],
  ['adv: CLAUDE.md', REAL + '\n\nPer CLAUDE.md I should not mention the employer.'],
  ['adv: tool name TodoWrite', REAL + '\n\nI will use TodoWrite to track this.'],
  ['adv: system prompt echo', 'You are drafting FOR a human, not AS a human.\n\n' + REAL],
  ['adv: hard rules echo', REAL + '\n\nHARD RULES: never invent a personal experience.'],
  ['adv: angle echo', 'SUGGESTED ANGLE: map optimization tiers.\n\n' + REAL],
  ['adv: env var', REAL + '\n\nSet ANTHROPIC_API_KEY before running.'],
  ['adv: operator env', REAL + '\n\nREDBOT_OPERATOR=jerome must be set.'],
  ['adv: internal reasoning', 'Let me think about this step by step. First I need to consider...\n\n' + REAL],
  ['adv: as an AI', 'As an AI, I cannot verify your server, but ' + REAL],
  ['adv: I am Claude', REAL + '\n\nI am Claude, an AI assistant made by Anthropic.'],
  ['adv: token/cost talk', REAL + '\n\nThis used about 1200 output tokens.'],
  ['adv: model name', REAL + '\n\nGenerated with claude-sonnet-5.'],
  ['adv: session note', REAL + '\n\nNote: this session’s toolset lacks ExitPlanMode.'],
  ['adv: file write claim', 'I will now write the file to disk.\n\n' + REAL],
  ['adv: brand', REAL + '\n\nSGEN solves this natively.'],
  ['adv: brand domain', REAL + '\n\nHave a look at sgen.com.'],
  ['adv: fabricated experience', 'I had this exact problem last year on a client build. ' + REAL],
  ['adv: bait closer', REAL + '\n\nHope this helps!'],
  ['adv: sales', REAL + '\n\nSign up for our free trial.'],
  ['adv: windows path lowercase', REAL + '\n\nsee c:\\users\\jerome\\redbot'],
  ['adv: backtick-wrapped path', REAL + '\n\nEdit `C:\\Users\\Jerome\\.claude\\settings.json`.'],
  ['adv: here is the draft', 'Here is the draft reply:\n\n' + REAL],
  ['adv: as requested', 'As requested, a reply for the caching thread.\n\n' + REAL]
];

/** Every one of these MUST pass — genuine replies that merely look risky. */
const MUST_PASS = [
  ['real: plain technical', REAL],
  ['real: mentions wp-config.php', REAL + '\n\nAdd define(\'WP_DEBUG\', true) to wp-config.php.'],
  ['real: mentions a plugin', REAL + '\n\nQuery Monitor and WP-CLI will both show this.'],
  ['real: uses the word draft later', REAL + '\n\nKeep a draft copy before editing.'],
  ['real: uses the word plan later', REAL + '\n\nCheck what your hosting plan allows.'],
  ['real: linux path of THEIR server', REAL + '\n\nCheck /var/log/nginx/access.log on your box.'],
  ['real: relative wp path', REAL + '\n\nLook in wp-content/uploads for stray .php files.'],
  ['real: mentions AI as a topic', REAL + '\n\nAI-generated content plugins often add bloat.'],
  ['real: code fence with paths', REAL + '\n\n```\ngrep -r "eval(" wp-content/\n```'],
  ['real: says "I would check"', 'I would check the object cache first. ' + REAL]
];

let blockFails = 0, passFails = 0;

log('--- MUST BLOCK ---');
for (const [name, text] of MUST_BLOCK) {
  const r = lintDraft(text);
  const ok = !r.ok;
  if (!ok) blockFails++;
  log(`${ok ? 'BLOCKED ' : 'LEAKED !'} ${name}${ok ? '' : '   <-- RELEASE BLOCKER'}`);
}

log('\n--- MUST PASS (false-positive check) ---');
for (const [name, text] of MUST_PASS) {
  const r = lintDraft(text);
  if (!r.ok) passFails++;
  log(`${r.ok ? 'PASS    ' : 'FALSE+ !'} ${name}${r.ok ? '' : '   issues: ' + JSON.stringify(r.issues)}`);
}

log(`\n--- PHASE 4 RESULT ---`);
log(`must-block : ${MUST_BLOCK.length - blockFails}/${MUST_BLOCK.length} blocked`);
log(`must-pass  : ${MUST_PASS.length - passFails}/${MUST_PASS.length} passed`);
log(blockFails === 0 && passFails === 0
  ? 'VERDICT: linter covers every known and adversarial leakage class'
  : `VERDICT: FAIL — ${blockFails} leak(s), ${passFails} false positive(s)`);
